/* double include preventer */
#ifndef _MSG_H
#define _MSG_H

/* file: msg.h, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: D:\TEMP\Cfg_Gen-1478620610143-3\OsProxyFiles-1478620672066-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Tue Nov 08 16:57:54 2016 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif


#endif   /* double include preventer */

/* END OF C:\CanCollege\AUTOSAR4\_S2_IO\Appl\GenDataVtt\msg.h */

