/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: D:\TEMP\Cfg_Gen-1478621047768-0\OsProxyFiles-1478621082383-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Tue Nov 08 17:04:44 2016 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\CanCollege\AUTOSAR4\_S5_MemoryAbstraction\Appl\GenDataVtt\msg.c */

