/* file: tcb.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: D:\TEMP\Cfg_Gen-1478621047768-0\OsProxyFiles-1478621082383-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Tue Nov 08 17:04:44 2016 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

/* Start of invariant part */
#if defined USE_QUOTE_INCLUDES
 #include "Os.h"
#else
 #include <Os.h>
#endif
#if defined USE_QUOTE_INCLUDES
 #include "osekext.h"
#else
 #include <osekext.h>
#endif

   /* structure for standard counter (derived from system clock) */
   osqROM0 osqROM1 const osqROM2 AlarmBaseType osqROM3 oskAlarmDefinitions=
   {
      (TickType) OSMAXALLOWEDVALUE,
      OSTICKSPERBASE,
      OSMINCYCLE
   };

   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmTime[osdNumberOfAlarms+osdNumberOfHiResSchedTabs];
   #if (osdUseHeap)
      #if (osdNumberOfAlarms>0)
         osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osAlarmActivated[osdNumberOfAlarms];
      #endif
      osqTcbRAM1 osqTcbRAM2 osHeapType osqTcbRAM3 osAlarmHeap[osdNumberOfVarHeapAlarms+osdNumberOfStatHeapAlarms+osdNumberOfHiResSchedTabs+1];    /* Minimum Heap */
   #endif

   osqTcbRAM1 osqTcbRAM2 TickType osqTcbRAM3 osAlarmCycleTime[osdNumberOfVarAlarms];

#if (osdNumberOfScheduleTables > 0)
   osqRAM0 osqRAM1 osqRAM2 osSTIndexType osqRAM3 osSTCurrentIndex[osdNumberOfScheduleTables];
   osqRAM0 osqRAM1 osqRAM2 osSTOffsetType osqRAM3 osSTCounter[osdNumberOfScheduleTables];
   osqRAM0 osqRAM1 osqRAM2 ScheduleTableStatusType osqRAM3 osSTState[osdNumberOfScheduleTables];
   osqRAM0 osqRAM1 osqRAM2 ScheduleTableType osqRAM3 osSTNextTable[osdNumberOfScheduleTables];
   osqRAM0 osqRAM1 osqRAM2 osuint8 osqRAM3 osHasBeenNexted[osdNumberOfScheduleTables];
#else
   osqRAM0 osqRAM1 osqRAM2 osSTIndexType osqRAM3 osSTCurrentIndex[1];
   osqRAM0 osqRAM1 osqRAM2 osSTOffsetType osqRAM3 osSTCounter[1];
   osqRAM0 osqRAM1 osqRAM2 ScheduleTableStatusType osqRAM3 osSTState[1];
   osqRAM0 osqRAM1 osqRAM2 ScheduleTableType osqRAM3 osSTNextTable[1];
   osqRAM0 osqRAM1 osqRAM2 osuint8 osqRAM3 osHasBeenNexted[1] = {0};
#endif
#if (CC==BCC2) || (CC==ECC2)
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[osdNumberOfPriorities];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskHead[1];
      osqTcbRAM1 osqTcbRAM2 osQEntryCountType osqTcbRAM3 osQReadyTaskTail[1];
   #endif
#else
   #if (osdNumberOfPriorities > 0)
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[osdNumberOfPriorities];
   #else
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQReadyTask[1];
   #endif
#endif

#if ((CC == BCC2) || (CC == ECC2))
   #if (osdNumberOfAllTasks > 0)
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[osdNumberOfAllTasks];
   #else
      osqTcbRAM1 osqTcbRAM2 osActivationCountType osqTcbRAM3 osTcbActivationCount[1];
   #endif
#endif

   osqRAM0 osqRAM1 osqRAM2 osPrioFlagType osqRAM3 osQReadyPrios[osdRTSize];

#if (osdNumberOfAllTasks > 0)
   osqTcbRAM1 osqTcbRAM2 osStackPtrType osqTcbRAM3 osTcbSP[osdNumberOfAllTasks];
#else
   osqTcbRAM1 osqTcbRAM2 osStackPtrType osqTcbRAM3 osTcbSP[1];
#endif
#if (osdNumberOfAllTasks > 0)
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[osdNumberOfAllTasks];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[osdNumberOfAllTasks];
   osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbORTIServiceId[osdNumberOfAllTasks];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
    #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
     osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbResourceCounter[osdNumberOfAllTasks];
     #endif
    #endif
   #endif
#else
   osqTcbRAM1 osqTcbRAM2 osTaskStateType osqTcbRAM3 osTcbTaskState[1];
   #if osdORTIDebug
   osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osTcbActualPrio[1];
   osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbORTIServiceId[1];
   #endif
   #if STATUS_LEVEL == EXTENDED_STATUS
   #if (osdNumberOfInternalResources > 0) || (osdNumberOfInterruptResources > 0)
   osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbResourceCounter[1];
    #else
     #if osdLib
      osqTcbRAM1 osqTcbRAM2 osuint8 osqTcbRAM3 osTcbResourceCounter[1];
     #endif
   #endif
   #endif
#endif


   #if ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))
      osqTcbRAM1 osqTcbRAM2 osPrioType osqTcbRAM3 osResSavedPrio[osdNumberOfAllResources];
   #endif /* ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed))) */
   #if STATUS_LEVEL == EXTENDED_STATUS && ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))
      osqTcbRAM1 osqTcbRAM2 osResCounterType osqTcbRAM3 osResOccupationCounter[osdNumberOfAllResources];
   #endif
   #if ((STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions && ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))) || osdORTIDebug
      osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osResActualTask[osdNumberOfAllResources];
   #endif


   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbWaitEventMask[osdNumberOfExtendedTasks];

#if ((osdSC == SC3) || (osdSC == SC4))
   osqTcbRAM1 osqTcbRAM2 ApplicationStateType osqTcbRAM3 osApplicationState [osdNumberOfApplications];
#endif

#if (osdNumberOfExtendedTasks > 0) || osdLib
   #if (osdNumberOfExtendedTasks == 0) && osdLib
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[1];
   #else
   osqTcbRAM1 osqTcbRAM2 EventMaskType osqTcbRAM3 osTcbSetEventMask[osdNumberOfExtendedTasks];
   #endif
#endif

#if osdLib
   osqROM0 osqROM1 const osqROM2 osRTSizeType    osqROM3 oskRTSize= osdRTSize;
   osqROM0 osqROM1 const osqROM2 osAppModeIndexType osqROM3 oskNumberOfAppModes=   osdNumberOfAppModes;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfAllTasks=      osdNumberOfAllTasks;
   osqROM0 osqROM1 const osqROM2 osTaskIndexType osqROM3 oskNumberOfExtendedTasks= osdNumberOfExtendedTasks;
   osqROM0 osqROM1 const osqROM2 osPrioType      osqROM3 oskNumberOfPriorities=    osdNumberOfPriorities;

   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfAllResources=       osdNumberOfAllResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfTaskResources=      osdNumberOfTaskResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInterruptResources= osdNumberOfInterruptResources;
   osqROM0 osqROM1 const osqROM2 osResourceIndexType osqROM3 oskNumberOfInternalResources=  osdNumberOfInternalResources;

   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfAlarms=       osdNumberOfAlarms;
   osqROM0 osqROM1 const osqROM2 osAlarmIndexType osqROM3 oskNumberOfVarAlarms=    osdNumberOfVarAlarms;
   
   osqROM0 osqROM1 const osqROM2 ScheduleTableType osqROM3 oskNumberOfScheduleTables=    osdNumberOfScheduleTables;
   osqROM0 osqROM1 const osqROM2 CounterType osqROM3 oskSystemTimer=                     SystemTimer;
   osqROM0 osqROM1 const osqROM2 CounterType osqROM3 oskNumberOfCounters=                osdNumberOfCounters;
   
   osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskMaxAllowedValue=    (TickType)OSMAXALLOWEDVALUE;
   osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskMinCycle=                     OSMINCYCLE;
   osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskTicksPerBase=                 OSTICKSPERBASE;

#endif
   osqROM0 osqROM1 const osqROM2 osVersionVariantCodingType osqROM3 oskLibVersionVariant=
   {
      0xAF, /* magic number */
      0xFE,
      0xDE,
      0xAD,
      (osuint8)osdVrmMajRelNumRef, /* version of operating system, Major, defined in vrm.h */
      (osuint8)osdVrmMinRelNumRef, /* version of operating system, Minor */
      (osuint8)osdVrmGenMajRelNumRef, /* version of code generator */
      (osuint8)osdVrmGenMinRelNumRef,
      (osuint8) ((osdVariantAssertionsEnabled << 7) | /* TR:SPMF12:0005 */ 
                 (osdVariantModulnamesEnabled << 6) |
                 (osdVariantStackcheck        << 5) |
                 (osdVariantSchedule          << 3) |
                 (osdVariantStatus            << 2) |
                  osdVariantCC),
      (osuint8)(((osdVariantSC)                    ) |
                ( 0                            << 2) |
                ( 0                            << 3) |
                ((osdVariantFeaturesUsed_Sync) << 4) |
                ((osdVariantFeaturesUsed_TP)   << 5)),
     (osuint8) (((osdVariantSC)               ) |
                ((osdVariantFeaturesUsed) << 2)),
   };

/* Task Names */
const char *oskTaskNames[] = 
{
   "SchM_Task",
   "IO_Task",
   "My_Task",
   "Init_Task",
};

/* End of invariant part */
#if defined osdUseGeneratedFastAlarm
#if ( (0 == osdUserDefinedSystemTimer) && (osdAlarmsOnSystemTimer != 0) )
/* MISRA RULE 8.10 VIOLATION: Depending on the configuration, this function may be called only in this module.
 * Declaring this function static for some configurations would increase code complexity, too much. */
osqFunc1 void osqFunc2 osWorkAlarms(void) /* PRQA S 1505 */
{
   osqPRAM1 osqPRAM2 TickType osqPRAM3 *aPtr = (osqPRAM1 osqPRAM2 TickType osqPRAM3 *) osAlarmTime; /* TR:SPMF20:0010 */ 
   osSaveDisableLevel();
   OS_TI_START_CRITICAL()
   if ((*aPtr) != 0)    /* Rte_Al_TE2_SchM_Task_0_10ms */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* Rte_Al_TE2_SchM_Task_0_10ms is expired */
         (*aPtr) = osAlarmCycleTime[Rte_Al_TE2_SchM_Task_0_10ms];
#if (osdUseHeap != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[Rte_Al_TE2_SchM_Task_0_10ms] = 0;
         }
#endif /* osdUseHeap */
         (void) osSysSetEvent(SchM_Task,Rte_Ev_Cyclic2_SchM_Task_0_10ms);

         OS_TI_END_CRITICAL()
         osRestoreEnableLevel();  /* enable interrupts */
         osSaveDisableLevel();  /* disable interrupts */
         OS_TI_START_CRITICAL()

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* Rte_Al_TE2_SchM_Task_0_20ms */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* Rte_Al_TE2_SchM_Task_0_20ms is expired */
         (*aPtr) = osAlarmCycleTime[Rte_Al_TE2_SchM_Task_0_20ms];
#if (osdUseHeap != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[Rte_Al_TE2_SchM_Task_0_20ms] = 0;
         }
#endif /* osdUseHeap */
         (void) osSysSetEvent(SchM_Task,Rte_Ev_Cyclic2_SchM_Task_0_20ms);

         OS_TI_END_CRITICAL()
         osRestoreEnableLevel();  /* enable interrupts */
         osSaveDisableLevel();  /* disable interrupts */
         OS_TI_START_CRITICAL()

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* Rte_Al_TE_CpApMySwc_RCtApMySwcCode */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* Rte_Al_TE_CpApMySwc_RCtApMySwcCode is expired */
         (*aPtr) = osAlarmCycleTime[Rte_Al_TE_CpApMySwc_RCtApMySwcCode];
#if (osdUseHeap != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[Rte_Al_TE_CpApMySwc_RCtApMySwcCode] = 0;
         }
#endif /* osdUseHeap */
         (void) osSysSetEvent(My_Task,Rte_Ev_Run_CpApMySwc_RCtApMySwcCode);

         OS_TI_END_CRITICAL()
         osRestoreEnableLevel();  /* enable interrupts */
         osSaveDisableLevel();  /* disable interrupts */
         OS_TI_START_CRITICAL()

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* Rte_Al_TE_IO_Task_0_200ms */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* Rte_Al_TE_IO_Task_0_200ms is expired */
         (*aPtr) = osAlarmCycleTime[Rte_Al_TE_IO_Task_0_200ms];
#if (osdUseHeap != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[Rte_Al_TE_IO_Task_0_200ms] = 0;
         }
#endif /* osdUseHeap */
         (void) osSysSetEvent(IO_Task,Rte_Ev_Cyclic_IO_Task_0_200ms);

         OS_TI_END_CRITICAL()
         osRestoreEnableLevel();  /* enable interrupts */
         osSaveDisableLevel();  /* disable interrupts */
         OS_TI_START_CRITICAL()

      }
   }

   aPtr+=1;

   if ((*aPtr) != 0)    /* Rte_Al_TE_Fee_Fee_MainFunction */
   {
      (*aPtr)--;
      if ((*aPtr) == 0)
      {
         /* Rte_Al_TE_Fee_Fee_MainFunction is expired */
         (*aPtr) = osAlarmCycleTime[Rte_Al_TE_Fee_Fee_MainFunction];
#if (osdUseHeap != 0)
         if( (*aPtr) == 0 )
         {
            osAlarmActivated[Rte_Al_TE_Fee_Fee_MainFunction] = 0;
         }
#endif /* osdUseHeap */
         (void) osSysSetEvent(SchM_Task,Rte_Ev_Run_Fee_Fee_MainFunction);

         OS_TI_END_CRITICAL()
         osRestoreEnableLevel();  /* enable interrupts */
         osSaveDisableLevel();  /* disable interrupts */
         OS_TI_START_CRITICAL()

      }
   }
   OS_TI_END_CRITICAL()
   osRestoreEnableLevel();
} /* END OF alarm checking function */
#endif /* ( (0==osdUserDefinedSystemTimer) &&  (osdAlarmsOnSystemTimer) ) */
#endif /* osdUseGeneratedFastAlarm */



#if (CC == BCC2) || (CC == ECC2)
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_0[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_1[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_2[2];
static osqTcbRAM1 osqTcbRAM2 TaskType osqTcbRAM3 osQTaskActivation_3[2];

osqROM0 osqPTcbRAM1 osqPTcbRAM2 TaskType osqPTcbRAM3 * osqROM1 const osqROM2 osqROM3 oskQActivationQueues[osdNumberOfPriorities]=
{
   osQTaskActivation_0,
   osQTaskActivation_1,
   osQTaskActivation_2,
   osQTaskActivation_3,
};

osqROM0 osqROM1 const osqROM2 osQEntryCountType osqROM3 oskQMaxActivations[osdNumberOfPriorities]=
{
   1,
   1,
   1,
   1,
};

#endif

osqROM0 osqROM1 const osqROM2 osTaskFlagType osqROM3 oskTcbTaskFlags[osdNumberOfAllTasks] = {
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
 osdTaskFlagScheduleAllowed,
};

osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskTcbAutoStart[osdNumberOfAllTasks] = {
   0x00, /* SchM_Task (extended) */
   0x00, /* IO_Task (extended) */
   0x00, /* My_Task (extended) */
   0x01, /* Init_Task (basic) */
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskTcbReadyPrioMask[osdNumberOfAllTasks] = {
   0x80000000UL, /* SchM_Task (extended) */
   0x20000000UL, /* IO_Task (extended) */
   0x10000000UL, /* My_Task (extended) */
   0x40000000UL, /* Init_Task (basic) */
};

osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskTcbReadyPrioOffset[osdNumberOfAllTasks] = {
   0x00,
   0x00,
   0x00,
   0x00,
};
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskTcbHomePrio[osdNumberOfAllTasks]=
{
   0, /* SchM_Task (extended)*/
   2, /* IO_Task (extended)*/
   3, /* My_Task (extended)*/
   1, /* Init_Task (basic)*/
};

#if (CC == BCC2) || (CC == ECC2)
osqROM0 osqROM1 const osqROM2 osActivationCountType osqROM3 oskTcbAllowedActivations[osdNumberOfAllTasks]=
{
   1, /* SchM_Task (extended)*/
   1, /* IO_Task (extended)*/
   1, /* My_Task (extended)*/
   1, /* Init_Task (basic)*/
};
#endif

#if (osdKillTaskIsrPossible || (osdSC== SC3) || (osdSC== SC4))
#if (osdNumberOfAllTasks > 0)
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osTcbLockedResource[osdNumberOfAllTasks];
#else
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osTcbLockedResource[1];
#endif
#endif

/* Resources */

#if ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed)))
#if (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions
osqROM0 osqROM1 const osqROM2 osResAccessMaskType osqROM3 oskResAccessMask[osdNumberOfAllResources][1]=
{
/* sequence of taskNumbers (!not priorities) */
   {    0x00000000UL,   } /* OsResource*/
};

#endif /* (STATUS_LEVEL == EXTENDED_STATUS) && osdEnableAssertions */

osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResCeilingPrio[osdNumberOfAllResources]=
{
   (osPrioType)-1, /* OsResource*/
};

#if (0 == osdNumberOfTaskResources)
osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResCeilingPrioMask[1]=
{
   0U
};

#else
osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResCeilingPrioMask[osdNumberOfTaskResources]=
{
   0x00000001UL,
};

#endif
#if (0 == osdNumberOfTaskResources)
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResCeilingPrioOffset[1]=
{
   0
};
#else
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResCeilingPrioOffset[osdNumberOfTaskResources]=
{
   0xff,
};
#endif
#endif /* ((!defined(osdGetResourceNotUsed)) || (!defined(osdReleaseResourceNotUsed))) */

#if (osdNumberOfAllTasks>0)
#if ((osdNumberOfInternalResources > 0)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[osdNumberOfAllTasks]=
{
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
   (osPrioType) 0,
};

osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
};

 #if ((osdRTSize > 1)||(osdLib==1))
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[osdNumberOfAllTasks]=
{
   0,
   0,
   0,
   0,
};

#endif
#endif

#else
osqROM0 osqROM1 const osqROM2 osPrioType osqROM3 oskResInternalCeilingPrio[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioFlagType osqROM3 oskResInternalCeilingPrioMask[1]={0};
osqROM0 osqROM1 const osqROM2 osPrioOffsetType osqROM3 oskResInternalCeilingPrioOffset[1]={0};
#endif
#if (osdKillTaskIsrPossible || (osdSC== SC3) || (osdSC== SC4))
#if (osdNumberOfAllResources > 0)
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osResNextLockedResource[osdNumberOfAllResources];
#else
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osResNextLockedResource[1];
#endif
#endif

/* Counters */

osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskCounterMaxAllowedValue[1]={
(TickType) OSMAXALLOWEDVALUE,
};
osqTcbRAM1 volatile osqTcbRAM2 TickType osqTcbRAM3 osCounter[1];

osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskCounterTicksPerBase[1]={
OSTICKSPERBASE,
};
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskCounterMinCycle[1]={
OSMINCYCLE,
};

osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskAlarmCounterRef[5]={
SystemTimer,
SystemTimer,
SystemTimer,
SystemTimer,
SystemTimer,
};

/*-+--------------------------------------------------------------------------
 / IncrementCounter                                                           
 / ================                                                           
 /                                                                            
 / Syntax:                                                                    
 /    StatusType IncrementCounter(CounterType CounterID)                      
 / Parameter (In):                                                            
 /   CounterType CounterID                                                    
 / Parameter (Out):                                                           
 /   none                                                                     
 / Description:                                                               
 /   This service increments the counter <CounterID> by one. If any alarm time
 /   or schedule table expiry point is reached by this increment, the         
 /   configured action (e.g. task activation) is performed.                   
 / Return value (depends on OIL-Attribute STATUS):                            
 /    STANDARD:                                                               
 /       - No error, E_OK                                                     
 /    EXTENDED:                                                               
 /       - <CounterID> not valid, E_OS_ID                                     
 /       - The service has been called with interrupts disabled,              
 /         E_OS_DISABLEDINT                                                   
 / Scalability Classes:                                                       
 /    SC1, SC2, SC3, SC4                                                      
 /--------------------------------------------------------------------------*/

/*
 * Sorry, no function IncrementCounter was generated, as no software counter exists.
 * (Only software counters can be incremented!)
 */

/* Alarms */

/* static alarm time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmTime[osdNumberOfAlarms]={
   0U, /* no static alarm: Rte_Al_TE2_SchM_Task_0_10ms*/
   0U, /* no static alarm: Rte_Al_TE2_SchM_Task_0_20ms*/
   0U, /* no static alarm: Rte_Al_TE_CpApMySwc_RCtApMySwcCode*/
   0U, /* no static alarm: Rte_Al_TE_IO_Task_0_200ms*/
   0U, /* no static alarm: Rte_Al_TE_Fee_Fee_MainFunction*/
};

/* static cycle time */
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskStaticAlarmCycleTime[osdNumberOfAlarms]={
   0, /* no static alarm: Rte_Al_TE2_SchM_Task_0_10ms */
   0, /* no static alarm: Rte_Al_TE2_SchM_Task_0_20ms */
   0, /* no static alarm: Rte_Al_TE_CpApMySwc_RCtApMySwcCode */
   0, /* no static alarm: Rte_Al_TE_IO_Task_0_200ms */
   0, /* no static alarm: Rte_Al_TE_Fee_Fee_MainFunction */
};

/* Autostart */
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskAlarmAutoStart[osdNumberOfAlarms]={
   0x00, /* Rte_Al_TE2_SchM_Task_0_10ms */
   0x00, /* Rte_Al_TE2_SchM_Task_0_20ms */
   0x00, /* Rte_Al_TE_CpApMySwc_RCtApMySwcCode */
   0x00, /* Rte_Al_TE_IO_Task_0_200ms */
   0x00, /* Rte_Al_TE_Fee_Fee_MainFunction */
};

const long oskTickTime= 1000; /* TickTime in Milliseconds */

/* Dummy osWorkAlarms() */
#if (osdAlarmsOnSystemTimer == 0)
osqFunc1 void osqFunc2 osWorkAlarms(void) {}
#endif

/* Schedule Tables */

#if (osdNumberOfScheduleTables > 0)
osqROM0 osqROM1 const osqROM2 CounterType osqROM3 oskCounterOfST[osdNumberOfScheduleTables]={
};

/* Length of ScheduleTable/Period of GlobalTime*/
osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskSTMaxAllowed[osdNumberOfScheduleTables]={
};
/* The array oskScheduleTableInitialOffset is necessary only to 
 * fullfill SASR30:0212. Our implementation does not need it anymore.   
 */
   osqROM0 osqROM1 const osqROM2 osSTOffsetType osqROM3 oskScheduleTableInitialOffset[osdNumberOfScheduleTables] = {
   
};
#else
   osqROM0 osqROM1 const osqROM2 CounterType osqROM3 oskCounterOfST[1] = {0};
   osqROM0 osqROM1 const osqROM2 osSTOffsetType osqROM3 oskScheduleTableInitialOffset[1] = {0};
#endif /*(osdNumberOfScheduleTables > 0)*/

#if (osdNumberOfScheduleTables > 0)
#if (osdNumberOfSTEntries > 0)
osqFunc1 osSTReactionType osqFunc2 osSTWorkActions(GlobalTimeTickType* diff, osSTIndexType CurrentEP)
{
   switch (CurrentEP)
   {
      /* MISRA RULE 14.1 VIOLATION: return is not
       * reachable but this is the only way for prevent a compiler warning (3201)
       */
      default:
         osSysErrAssertFailed(osdErrWSUnknownAction)
         return osdSTReact_Stop;  /* PRQA S 3201 */
   }
}
#endif /*(osdNumberOfSTEntries > 0)*/

#else
osqFunc1 osuint8 osqFunc2 osSTWorkActions(GlobalTimeTickType* diff, osSTIndexType CurrentEP) /* osuint8 because osSTReactionType is not defined */
{
   diff = diff;            //  avoid visual c++ compiler warning C4100
   CurrentEP = CurrentEP;  //  avoid visual c++ compiler warning C4100
   return 0;
}
#endif /*(osdNumberOfScheduleTables > 0)*/

#if (osdNumberOfScheduleTables > 0)
osqROM0 osqROM1 const osqROM2 osSTIndexType osqROM3 oskSTStartIndex[osdNumberOfScheduleTables]={
};
#else
   osqROM0 osqROM1 const osqROM2 osSTIndexType osqROM3 oskSTStartIndex[1] = {0};
#endif /*(osdNumberOfScheduleTables > 0)*/

osqROM0 osqROM1 const osqROM2 TickType osqROM3 oskAutostartScheduleTableOffset[1]={0}; /* no ScheduleTables, 1 as default */
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskScheduleTableAutoStart[1]={0};
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskScheduleTableAutoStartType[1]={0};
#if (STATUS_LEVEL == EXTENDED_STATUS)
osqROM0 osqROM1 const osqROM2 osuint8 osqROM3 oskSTSyncKind[1]={0}; /* no ScheduleTables, 1 as default */
#endif /*(STATUS_LEVEL == EXTENDED_STATUS)*/
/* Hook routines */

#if ((defined osdTestMacros) || osdLib || (osdSC== SC3) || (osdSC== SC4))
/* MISRA RULE 14.1 not violated: osInterPreTaskHook might be called from assembly on 
 * some platforms. (1503) */

osqFunc1 void osqFunc2 osInterPreTaskHook(void) /* PRQA S 1503 */
{
} /* END OF osInterPreTaskHook */
/* MISRA RULE 14.1 not violated: osInterPostTaskHook might be called from assembly on 
 * some platforms. (1503) */

osqFunc1 void osqFunc2 osInterPostTaskHook(void) /* PRQA S 1503 */
{
} /* END OF osInterPostTaskHook */
#endif /*((defined osdTestMacros) || osdLib || (osdSC== SC3) || (osdSC== SC4))*/

#if (osdLib || (osdSC== SC3) || (osdSC== SC4))
/* MISRA RULE 14.1 VIOLATION: osInterErrorHook might be not called in some
 * configurations. Conditional compiling of the function would increase
 * the code complexity to unacceptable level (1503) */
void osInterErrorHook(StatusType Error)   /* PRQA S 1503 */
{
   /* osdDummyRead might intentionally assign a value to an unused variable on
    * some platforms to avoid compiler warnings. This is no MISRA error. (3199) */
   osdDummyRead(Error)   /* PRQA S 3199 */
} /* END OF osInterErrorHook */
/* MISRA RULE 14.1 VIOLATION: osInterStartupHook might be not called in some
 * configurations. Conditional compiling of the function would increase
 * the code complexity to unacceptable level (1503) */

void osInterStartupHook(void)   /* PRQA S 1503 */
{
} /* END OF osInterStartupHook */
/* MISRA RULE 14.1 VIOLATION: osInterShutdownHook might be not called in some
 * configurations. Conditional compiling of the function would increase
 * the code complexity to unacceptable level (1503) */

osqFunc1 void osqFunc2 osInterShutdownHook(StatusType Error)   /* PRQA S 1503 */
{
#if ((osdSC== SC3) || (osdSC== SC4))
   osuint16 savedContext;

   osInSystemFct = osdTRUE;
   savedContext = osCurrentContext;
   osCurrentContext = osdCtxShutdownHook;
#endif
   ShutdownHook(Error);
#if ((osdSC== SC3) || (osdSC== SC4))
   osCurrentContext = savedContext;
   osInSystemFct = osdFALSE;
#endif
} /* END OF osInterShutdownHook */
/* MISRA RULE 14.1 VIOLATION: osInterCOMErrorHook might be not called in some
 * configurations. Conditional compiling of the function would increase
 * the code complexity to unacceptable level (1503) */

osqFunc1 void osqFunc2 osInterCOMErrorHook(StatusType Error)   /* PRQA S 1503 */
{
   /* osdDummyRead might intentionally assign a value to an unused variable on
    * some platforms to avoid compiler warnings. This is no MISRA error. (3199) */
   osdDummyRead(Error)   /* PRQA S 3199 */
} /* END OF osInterCOMErrorHook */

#endif
#if (osdKillTaskIsrPossible || (osdSC== SC3) || (osdSC== SC4))
#if (osdNumberOfCat2ISRs > 0)
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osIcbLockedResource[osdNumberOfCat2ISRs];
#else
   osqTcbRAM1 osqTcbRAM2 osResourceIndexType osqTcbRAM3 osIcbLockedResource[1];
#endif
#endif

/* Interrupt handler prototypes */

void CanIsrWakeup_0func(void);
void CanIsrTx_0func(void);
void CanIsrErr_0func(void);
void CanIsrRx_0func(void);
void osTimerInterruptfunc(void);

/* ISR configuration */

extern void osISRUnhandledException(void);

const ISRConfigType ISRConfig[] = 
{
   { "osTimerInterrupt", &osTimerInterruptfunc, 4, 2, 1, 0 },  /* 0: SystemTimer */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 1: RESERVED_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 2: RESERVED_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 3: RESERVED_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 4: RESERVED_3 */
   { "CanIsrTx_0", &CanIsrTx_0func, 1, 2, 31, 0 },  /* 5: CanIsrTx_0 */
   { "CanIsrRx_0", &CanIsrRx_0func, 3, 2, 31, 0 },  /* 6: CanIsrRx_0 */
   { "CanIsrErr_0", &CanIsrErr_0func, 2, 2, 31, 0 },  /* 7: CanIsrErr_0 */
   { "CanIsrWakeup_0", &CanIsrWakeup_0func, 0, 2, 31, 0 },  /* 8: CanIsrWakeup_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 9: CanIsrTx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 10: CanIsrRx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 11: CanIsrErr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 12: CanIsrWakeup_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 13: CanIsrTx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 14: CanIsrRx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 15: CanIsrErr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 16: CanIsrWakeup_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 17: CanIsrTx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 18: CanIsrRx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 19: CanIsrErr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 20: CanIsrWakeup_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 21: CanIsrTx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 22: CanIsrRx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 23: CanIsrErr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 24: CanIsrWakeup_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 25: CanIsrTx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 26: CanIsrRx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 27: CanIsrErr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 28: CanIsrWakeup_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 29: CanIsrTx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 30: CanIsrRx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 31: CanIsrErr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 32: CanIsrWakeup_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 33: CanIsrTx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 34: CanIsrRx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 35: CanIsrErr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 36: CanIsrWakeup_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 37: CanIsrTx_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 38: CanIsrRx_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 39: CanIsrErr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 40: CanIsrWakeup_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 41: CanIsrTx_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 42: CanIsrRx_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 43: CanIsrErr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 44: CanIsrWakeup_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 45: CanIsrTx_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 46: CanIsrRx_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 47: CanIsrErr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 48: CanIsrWakeup_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 49: CanIsrTx_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 50: CanIsrRx_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 51: CanIsrErr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 52: CanIsrWakeup_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 53: CanIsrTx_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 54: CanIsrRx_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 55: CanIsrErr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 56: CanIsrWakeup_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 57: CanIsrTx_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 58: CanIsrRx_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 59: CanIsrErr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 60: CanIsrWakeup_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 61: CanIsrTx_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 62: CanIsrRx_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 63: CanIsrErr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 64: CanIsrWakeup_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 65: CanIsrTx_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 66: CanIsrRx_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 67: CanIsrErr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 68: CanIsrWakeup_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 69: LinIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 70: LinIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 71: LinIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 72: LinIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 73: LinIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 74: LinIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 75: LinIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 76: LinIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 77: LinIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 78: LinIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 79: LinIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 80: LinIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 81: LinIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 82: LinIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 83: LinIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 84: LinIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 85: LinIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 86: LinIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 87: LinIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 88: LinIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 89: LinIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 90: LinIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 91: LinIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 92: LinIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 93: LinIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 94: LinIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 95: LinIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 96: LinIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 97: LinIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 98: LinIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 99: LinIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 100: LinIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 101: EthIsrRx_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 102: EthIsrTx_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 103: EthIsrRx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 104: EthIsrTx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 105: EthIsrRx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 106: EthIsrTx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 107: EthIsrRx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 108: EthIsrTx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 109: EthIsrRx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 110: EthIsrTx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 111: EthIsrRx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 112: EthIsrTx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 113: EthIsrRx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 114: EthIsrTx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 115: EthIsrRx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 116: EthIsrTx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 117: Fr_IrqLine0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 118: Fr_IrqTimer0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 119: Fr_IrqLine1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 120: Fr_IrqTimer1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 121: Fr_IrqLine2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 122: Fr_IrqTimer2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 123: VttSysVarIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 124: GptIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 125: GptIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 126: GptIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 127: GptIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 128: GptIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 129: GptIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 130: GptIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 131: GptIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 132: GptIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 133: GptIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 134: GptIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 135: GptIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 136: GptIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 137: GptIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 138: GptIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 139: GptIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 140: GptIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 141: GptIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 142: GptIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 143: GptIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 144: GptIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 145: GptIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 146: GptIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 147: GptIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 148: GptIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 149: GptIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 150: GptIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 151: GptIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 152: GptIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 153: GptIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 154: GptIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 155: GptIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 156: GptIsr_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 157: GptIsr_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 158: GptIsr_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 159: GptIsr_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 160: GptIsr_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 161: GptIsr_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 162: GptIsr_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 163: GptIsr_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 164: GptIsr_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 165: GptIsr_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 166: GptIsr_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 167: GptIsr_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 168: GptIsr_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 169: GptIsr_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 170: GptIsr_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 171: GptIsr_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 172: GptIsr_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 173: GptIsr_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 174: AdcIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 175: AdcIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 176: AdcIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 177: AdcIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 178: AdcIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 179: AdcIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 180: AdcIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 181: AdcIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 182: AdcIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 183: AdcIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 184: AdcIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 185: AdcIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 186: AdcIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 187: AdcIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 188: AdcIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 189: AdcIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 190: AdcIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 191: AdcIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 192: AdcIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 193: AdcIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 194: AdcIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 195: AdcIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 196: AdcIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 197: AdcIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 198: AdcIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 199: AdcIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 200: AdcIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 201: AdcIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 202: AdcIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 203: AdcIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 204: AdcIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 205: AdcIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 206: AdcIsr_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 207: AdcIsr_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 208: AdcIsr_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 209: AdcIsr_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 210: AdcIsr_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 211: AdcIsr_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 212: AdcIsr_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 213: AdcIsr_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 214: AdcIsr_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 215: AdcIsr_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 216: AdcIsr_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 217: AdcIsr_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 218: AdcIsr_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 219: AdcIsr_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 220: AdcIsr_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 221: AdcIsr_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 222: AdcIsr_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 223: AdcIsr_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 224: IcuIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 225: IcuIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 226: IcuIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 227: IcuIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 228: IcuIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 229: IcuIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 230: IcuIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 231: IcuIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 232: IcuIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 233: IcuIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 234: IcuIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 235: IcuIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 236: IcuIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 237: IcuIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 238: IcuIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 239: IcuIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 240: IcuIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 241: IcuIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 242: IcuIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 243: IcuIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 244: IcuIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 245: IcuIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 246: IcuIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 247: IcuIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 248: IcuIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 249: IcuIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 250: IcuIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 251: IcuIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 252: IcuIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 253: IcuIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 254: IcuIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 255: IcuIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 256: IcuIsr_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 257: IcuIsr_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 258: IcuIsr_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 259: IcuIsr_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 260: IcuIsr_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 261: IcuIsr_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 262: IcuIsr_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 263: IcuIsr_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 264: IcuIsr_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 265: IcuIsr_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 266: IcuIsr_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 267: IcuIsr_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 268: IcuIsr_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 269: IcuIsr_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 270: IcuIsr_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 271: IcuIsr_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 272: IcuIsr_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 273: IcuIsr_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 274: PwmIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 275: PwmIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 276: PwmIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 277: PwmIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 278: PwmIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 279: PwmIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 280: PwmIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 281: PwmIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 282: PwmIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 283: PwmIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 284: PwmIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 285: PwmIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 286: PwmIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 287: PwmIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 288: PwmIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 289: PwmIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 290: PwmIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 291: PwmIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 292: PwmIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 293: PwmIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 294: PwmIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 295: PwmIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 296: PwmIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 297: PwmIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 298: PwmIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 299: PwmIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 300: PwmIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 301: PwmIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 302: PwmIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 303: PwmIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 304: PwmIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 305: PwmIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 306: PwmIsr_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 307: PwmIsr_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 308: PwmIsr_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 309: PwmIsr_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 310: PwmIsr_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 311: PwmIsr_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 312: PwmIsr_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 313: PwmIsr_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 314: PwmIsr_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 315: PwmIsr_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 316: PwmIsr_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 317: PwmIsr_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 318: PwmIsr_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 319: PwmIsr_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 320: PwmIsr_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 321: PwmIsr_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 322: PwmIsr_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 323: PwmIsr_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 324: SpiIsrTx_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 325: SpiIsrRx_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 326: SpiIsrTx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 327: SpiIsrRx_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 328: SpiIsrTx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 329: SpiIsrRx_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 330: SpiIsrTx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 331: SpiIsrRx_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 332: SpiIsrTx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 333: SpiIsrRx_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 334: SpiIsrTx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 335: SpiIsrRx_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 336: SpiIsrTx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 337: SpiIsrRx_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 338: SpiIsrTx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 339: SpiIsrRx_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 340: SpiIsrTx_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 341: SpiIsrRx_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 342: SpiIsrTx_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 343: SpiIsrRx_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 344: SpiIsrTx_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 345: SpiIsrRx_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 346: SpiIsrTx_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 347: SpiIsrRx_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 348: SpiIsrTx_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 349: SpiIsrRx_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 350: SpiIsrTx_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 351: SpiIsrRx_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 352: SpiIsrTx_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 353: SpiIsrRx_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 354: SpiIsrTx_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 355: SpiIsrRx_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 356: SpiIsrTx_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 357: SpiIsrRx_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 358: SpiIsrTx_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 359: SpiIsrRx_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 360: SpiIsrTx_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 361: SpiIsrRx_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 362: SpiIsrTx_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 363: SpiIsrRx_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 364: SpiIsrTx_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 365: SpiIsrRx_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 366: SpiIsrTx_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 367: SpiIsrRx_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 368: SpiIsrTx_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 369: SpiIsrRx_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 370: SpiIsrTx_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 371: SpiIsrRx_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 372: SpiIsrTx_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 373: SpiIsrRx_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 374: SpiIsrTx_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 375: SpiIsrRx_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 376: SpiIsrTx_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 377: SpiIsrRx_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 378: SpiIsrTx_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 379: SpiIsrRx_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 380: SpiIsrTx_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 381: SpiIsrRx_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 382: SpiIsrTx_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 383: SpiIsrRx_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 384: SpiIsrTx_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 385: SpiIsrRx_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 386: SpiIsrTx_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 387: SpiIsrRx_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 388: SpiIsrTx_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 389: SpiIsrRx_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 390: SpiIsrTx_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 391: SpiIsrRx_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 392: SpiIsrTx_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 393: SpiIsrRx_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 394: SpiIsrTx_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 395: SpiIsrRx_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 396: SpiIsrTx_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 397: SpiIsrRx_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 398: SpiIsrTx_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 399: SpiIsrRx_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 400: SpiIsrTx_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 401: SpiIsrRx_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 402: SpiIsrTx_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 403: SpiIsrRx_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 404: SpiIsrTx_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 405: SpiIsrRx_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 406: SpiIsrTx_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 407: SpiIsrRx_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 408: SpiIsrTx_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 409: SpiIsrRx_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 410: SpiIsrTx_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 411: SpiIsrRx_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 412: SpiIsrTx_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 413: SpiIsrRx_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 414: SpiIsrTx_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 415: SpiIsrRx_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 416: SpiIsrTx_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 417: SpiIsrRx_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 418: SpiIsrTx_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 419: SpiIsrRx_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 420: SpiIsrTx_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 421: SpiIsrRx_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 422: SpiIsrTx_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 423: SpiIsrRx_49 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 424: CddIsr_0 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 425: CddIsr_1 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 426: CddIsr_2 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 427: CddIsr_3 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 428: CddIsr_4 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 429: CddIsr_5 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 430: CddIsr_6 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 431: CddIsr_7 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 432: CddIsr_8 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 433: CddIsr_9 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 434: CddIsr_10 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 435: CddIsr_11 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 436: CddIsr_12 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 437: CddIsr_13 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 438: CddIsr_14 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 439: CddIsr_15 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 440: CddIsr_16 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 441: CddIsr_17 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 442: CddIsr_18 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 443: CddIsr_19 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 444: CddIsr_20 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 445: CddIsr_21 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 446: CddIsr_22 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 447: CddIsr_23 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 448: CddIsr_24 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 449: CddIsr_25 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 450: CddIsr_26 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 451: CddIsr_27 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 452: CddIsr_28 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 453: CddIsr_29 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 454: CddIsr_30 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 455: CddIsr_31 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 456: CddIsr_32 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 457: CddIsr_33 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 458: CddIsr_34 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 459: CddIsr_35 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 460: CddIsr_36 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 461: CddIsr_37 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 462: CddIsr_38 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 463: CddIsr_39 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 464: CddIsr_40 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 465: CddIsr_41 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 466: CddIsr_42 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 467: CddIsr_43 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 468: CddIsr_44 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 469: CddIsr_45 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 470: CddIsr_46 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 471: CddIsr_47 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 472: CddIsr_48 */
   { (char*)0, &osISRUnhandledException, 0, 0, 0, 0 },  /* 473: CddIsr_49 */
};

const osuint16 oskNumberOfInterruptSources = 474;

/* Variable to save the interrupt number which causes an Unhandled exception */
osuint16 osISRUnhandledException_Number;

const char* ISRNameTable[] =
{
  /* 0: */ "SystemTimer",
  /* 1: */ "RESERVED_0",
  /* 2: */ "RESERVED_1",
  /* 3: */ "RESERVED_2",
  /* 4: */ "RESERVED_3",
  /* 5: */ "CanIsrTx_0",
  /* 6: */ "CanIsrRx_0",
  /* 7: */ "CanIsrErr_0",
  /* 8: */ "CanIsrWakeup_0",
  /* 9: */ "CanIsrTx_1",
  /* 10: */ "CanIsrRx_1",
  /* 11: */ "CanIsrErr_1",
  /* 12: */ "CanIsrWakeup_1",
  /* 13: */ "CanIsrTx_2",
  /* 14: */ "CanIsrRx_2",
  /* 15: */ "CanIsrErr_2",
  /* 16: */ "CanIsrWakeup_2",
  /* 17: */ "CanIsrTx_3",
  /* 18: */ "CanIsrRx_3",
  /* 19: */ "CanIsrErr_3",
  /* 20: */ "CanIsrWakeup_3",
  /* 21: */ "CanIsrTx_4",
  /* 22: */ "CanIsrRx_4",
  /* 23: */ "CanIsrErr_4",
  /* 24: */ "CanIsrWakeup_4",
  /* 25: */ "CanIsrTx_5",
  /* 26: */ "CanIsrRx_5",
  /* 27: */ "CanIsrErr_5",
  /* 28: */ "CanIsrWakeup_5",
  /* 29: */ "CanIsrTx_6",
  /* 30: */ "CanIsrRx_6",
  /* 31: */ "CanIsrErr_6",
  /* 32: */ "CanIsrWakeup_6",
  /* 33: */ "CanIsrTx_7",
  /* 34: */ "CanIsrRx_7",
  /* 35: */ "CanIsrErr_7",
  /* 36: */ "CanIsrWakeup_7",
  /* 37: */ "CanIsrTx_8",
  /* 38: */ "CanIsrRx_8",
  /* 39: */ "CanIsrErr_8",
  /* 40: */ "CanIsrWakeup_8",
  /* 41: */ "CanIsrTx_9",
  /* 42: */ "CanIsrRx_9",
  /* 43: */ "CanIsrErr_9",
  /* 44: */ "CanIsrWakeup_9",
  /* 45: */ "CanIsrTx_10",
  /* 46: */ "CanIsrRx_10",
  /* 47: */ "CanIsrErr_10",
  /* 48: */ "CanIsrWakeup_10",
  /* 49: */ "CanIsrTx_11",
  /* 50: */ "CanIsrRx_11",
  /* 51: */ "CanIsrErr_11",
  /* 52: */ "CanIsrWakeup_11",
  /* 53: */ "CanIsrTx_12",
  /* 54: */ "CanIsrRx_12",
  /* 55: */ "CanIsrErr_12",
  /* 56: */ "CanIsrWakeup_12",
  /* 57: */ "CanIsrTx_13",
  /* 58: */ "CanIsrRx_13",
  /* 59: */ "CanIsrErr_13",
  /* 60: */ "CanIsrWakeup_13",
  /* 61: */ "CanIsrTx_14",
  /* 62: */ "CanIsrRx_14",
  /* 63: */ "CanIsrErr_14",
  /* 64: */ "CanIsrWakeup_14",
  /* 65: */ "CanIsrTx_15",
  /* 66: */ "CanIsrRx_15",
  /* 67: */ "CanIsrErr_15",
  /* 68: */ "CanIsrWakeup_15",
  /* 69: */ "LinIsr_0",
  /* 70: */ "LinIsr_1",
  /* 71: */ "LinIsr_2",
  /* 72: */ "LinIsr_3",
  /* 73: */ "LinIsr_4",
  /* 74: */ "LinIsr_5",
  /* 75: */ "LinIsr_6",
  /* 76: */ "LinIsr_7",
  /* 77: */ "LinIsr_8",
  /* 78: */ "LinIsr_9",
  /* 79: */ "LinIsr_10",
  /* 80: */ "LinIsr_11",
  /* 81: */ "LinIsr_12",
  /* 82: */ "LinIsr_13",
  /* 83: */ "LinIsr_14",
  /* 84: */ "LinIsr_15",
  /* 85: */ "LinIsr_16",
  /* 86: */ "LinIsr_17",
  /* 87: */ "LinIsr_18",
  /* 88: */ "LinIsr_19",
  /* 89: */ "LinIsr_20",
  /* 90: */ "LinIsr_21",
  /* 91: */ "LinIsr_22",
  /* 92: */ "LinIsr_23",
  /* 93: */ "LinIsr_24",
  /* 94: */ "LinIsr_25",
  /* 95: */ "LinIsr_26",
  /* 96: */ "LinIsr_27",
  /* 97: */ "LinIsr_28",
  /* 98: */ "LinIsr_29",
  /* 99: */ "LinIsr_30",
  /* 100: */ "LinIsr_31",
  /* 101: */ "EthIsrRx_0",
  /* 102: */ "EthIsrTx_0",
  /* 103: */ "EthIsrRx_1",
  /* 104: */ "EthIsrTx_1",
  /* 105: */ "EthIsrRx_2",
  /* 106: */ "EthIsrTx_2",
  /* 107: */ "EthIsrRx_3",
  /* 108: */ "EthIsrTx_3",
  /* 109: */ "EthIsrRx_4",
  /* 110: */ "EthIsrTx_4",
  /* 111: */ "EthIsrRx_5",
  /* 112: */ "EthIsrTx_5",
  /* 113: */ "EthIsrRx_6",
  /* 114: */ "EthIsrTx_6",
  /* 115: */ "EthIsrRx_7",
  /* 116: */ "EthIsrTx_7",
  /* 117: */ "Fr_IrqLine0",
  /* 118: */ "Fr_IrqTimer0",
  /* 119: */ "Fr_IrqLine1",
  /* 120: */ "Fr_IrqTimer1",
  /* 121: */ "Fr_IrqLine2",
  /* 122: */ "Fr_IrqTimer2",
  /* 123: */ "VttSysVarIsr_0",
  /* 124: */ "GptIsr_0",
  /* 125: */ "GptIsr_1",
  /* 126: */ "GptIsr_2",
  /* 127: */ "GptIsr_3",
  /* 128: */ "GptIsr_4",
  /* 129: */ "GptIsr_5",
  /* 130: */ "GptIsr_6",
  /* 131: */ "GptIsr_7",
  /* 132: */ "GptIsr_8",
  /* 133: */ "GptIsr_9",
  /* 134: */ "GptIsr_10",
  /* 135: */ "GptIsr_11",
  /* 136: */ "GptIsr_12",
  /* 137: */ "GptIsr_13",
  /* 138: */ "GptIsr_14",
  /* 139: */ "GptIsr_15",
  /* 140: */ "GptIsr_16",
  /* 141: */ "GptIsr_17",
  /* 142: */ "GptIsr_18",
  /* 143: */ "GptIsr_19",
  /* 144: */ "GptIsr_20",
  /* 145: */ "GptIsr_21",
  /* 146: */ "GptIsr_22",
  /* 147: */ "GptIsr_23",
  /* 148: */ "GptIsr_24",
  /* 149: */ "GptIsr_25",
  /* 150: */ "GptIsr_26",
  /* 151: */ "GptIsr_27",
  /* 152: */ "GptIsr_28",
  /* 153: */ "GptIsr_29",
  /* 154: */ "GptIsr_30",
  /* 155: */ "GptIsr_31",
  /* 156: */ "GptIsr_32",
  /* 157: */ "GptIsr_33",
  /* 158: */ "GptIsr_34",
  /* 159: */ "GptIsr_35",
  /* 160: */ "GptIsr_36",
  /* 161: */ "GptIsr_37",
  /* 162: */ "GptIsr_38",
  /* 163: */ "GptIsr_39",
  /* 164: */ "GptIsr_40",
  /* 165: */ "GptIsr_41",
  /* 166: */ "GptIsr_42",
  /* 167: */ "GptIsr_43",
  /* 168: */ "GptIsr_44",
  /* 169: */ "GptIsr_45",
  /* 170: */ "GptIsr_46",
  /* 171: */ "GptIsr_47",
  /* 172: */ "GptIsr_48",
  /* 173: */ "GptIsr_49",
  /* 174: */ "AdcIsr_0",
  /* 175: */ "AdcIsr_1",
  /* 176: */ "AdcIsr_2",
  /* 177: */ "AdcIsr_3",
  /* 178: */ "AdcIsr_4",
  /* 179: */ "AdcIsr_5",
  /* 180: */ "AdcIsr_6",
  /* 181: */ "AdcIsr_7",
  /* 182: */ "AdcIsr_8",
  /* 183: */ "AdcIsr_9",
  /* 184: */ "AdcIsr_10",
  /* 185: */ "AdcIsr_11",
  /* 186: */ "AdcIsr_12",
  /* 187: */ "AdcIsr_13",
  /* 188: */ "AdcIsr_14",
  /* 189: */ "AdcIsr_15",
  /* 190: */ "AdcIsr_16",
  /* 191: */ "AdcIsr_17",
  /* 192: */ "AdcIsr_18",
  /* 193: */ "AdcIsr_19",
  /* 194: */ "AdcIsr_20",
  /* 195: */ "AdcIsr_21",
  /* 196: */ "AdcIsr_22",
  /* 197: */ "AdcIsr_23",
  /* 198: */ "AdcIsr_24",
  /* 199: */ "AdcIsr_25",
  /* 200: */ "AdcIsr_26",
  /* 201: */ "AdcIsr_27",
  /* 202: */ "AdcIsr_28",
  /* 203: */ "AdcIsr_29",
  /* 204: */ "AdcIsr_30",
  /* 205: */ "AdcIsr_31",
  /* 206: */ "AdcIsr_32",
  /* 207: */ "AdcIsr_33",
  /* 208: */ "AdcIsr_34",
  /* 209: */ "AdcIsr_35",
  /* 210: */ "AdcIsr_36",
  /* 211: */ "AdcIsr_37",
  /* 212: */ "AdcIsr_38",
  /* 213: */ "AdcIsr_39",
  /* 214: */ "AdcIsr_40",
  /* 215: */ "AdcIsr_41",
  /* 216: */ "AdcIsr_42",
  /* 217: */ "AdcIsr_43",
  /* 218: */ "AdcIsr_44",
  /* 219: */ "AdcIsr_45",
  /* 220: */ "AdcIsr_46",
  /* 221: */ "AdcIsr_47",
  /* 222: */ "AdcIsr_48",
  /* 223: */ "AdcIsr_49",
  /* 224: */ "IcuIsr_0",
  /* 225: */ "IcuIsr_1",
  /* 226: */ "IcuIsr_2",
  /* 227: */ "IcuIsr_3",
  /* 228: */ "IcuIsr_4",
  /* 229: */ "IcuIsr_5",
  /* 230: */ "IcuIsr_6",
  /* 231: */ "IcuIsr_7",
  /* 232: */ "IcuIsr_8",
  /* 233: */ "IcuIsr_9",
  /* 234: */ "IcuIsr_10",
  /* 235: */ "IcuIsr_11",
  /* 236: */ "IcuIsr_12",
  /* 237: */ "IcuIsr_13",
  /* 238: */ "IcuIsr_14",
  /* 239: */ "IcuIsr_15",
  /* 240: */ "IcuIsr_16",
  /* 241: */ "IcuIsr_17",
  /* 242: */ "IcuIsr_18",
  /* 243: */ "IcuIsr_19",
  /* 244: */ "IcuIsr_20",
  /* 245: */ "IcuIsr_21",
  /* 246: */ "IcuIsr_22",
  /* 247: */ "IcuIsr_23",
  /* 248: */ "IcuIsr_24",
  /* 249: */ "IcuIsr_25",
  /* 250: */ "IcuIsr_26",
  /* 251: */ "IcuIsr_27",
  /* 252: */ "IcuIsr_28",
  /* 253: */ "IcuIsr_29",
  /* 254: */ "IcuIsr_30",
  /* 255: */ "IcuIsr_31",
  /* 256: */ "IcuIsr_32",
  /* 257: */ "IcuIsr_33",
  /* 258: */ "IcuIsr_34",
  /* 259: */ "IcuIsr_35",
  /* 260: */ "IcuIsr_36",
  /* 261: */ "IcuIsr_37",
  /* 262: */ "IcuIsr_38",
  /* 263: */ "IcuIsr_39",
  /* 264: */ "IcuIsr_40",
  /* 265: */ "IcuIsr_41",
  /* 266: */ "IcuIsr_42",
  /* 267: */ "IcuIsr_43",
  /* 268: */ "IcuIsr_44",
  /* 269: */ "IcuIsr_45",
  /* 270: */ "IcuIsr_46",
  /* 271: */ "IcuIsr_47",
  /* 272: */ "IcuIsr_48",
  /* 273: */ "IcuIsr_49",
  /* 274: */ "PwmIsr_0",
  /* 275: */ "PwmIsr_1",
  /* 276: */ "PwmIsr_2",
  /* 277: */ "PwmIsr_3",
  /* 278: */ "PwmIsr_4",
  /* 279: */ "PwmIsr_5",
  /* 280: */ "PwmIsr_6",
  /* 281: */ "PwmIsr_7",
  /* 282: */ "PwmIsr_8",
  /* 283: */ "PwmIsr_9",
  /* 284: */ "PwmIsr_10",
  /* 285: */ "PwmIsr_11",
  /* 286: */ "PwmIsr_12",
  /* 287: */ "PwmIsr_13",
  /* 288: */ "PwmIsr_14",
  /* 289: */ "PwmIsr_15",
  /* 290: */ "PwmIsr_16",
  /* 291: */ "PwmIsr_17",
  /* 292: */ "PwmIsr_18",
  /* 293: */ "PwmIsr_19",
  /* 294: */ "PwmIsr_20",
  /* 295: */ "PwmIsr_21",
  /* 296: */ "PwmIsr_22",
  /* 297: */ "PwmIsr_23",
  /* 298: */ "PwmIsr_24",
  /* 299: */ "PwmIsr_25",
  /* 300: */ "PwmIsr_26",
  /* 301: */ "PwmIsr_27",
  /* 302: */ "PwmIsr_28",
  /* 303: */ "PwmIsr_29",
  /* 304: */ "PwmIsr_30",
  /* 305: */ "PwmIsr_31",
  /* 306: */ "PwmIsr_32",
  /* 307: */ "PwmIsr_33",
  /* 308: */ "PwmIsr_34",
  /* 309: */ "PwmIsr_35",
  /* 310: */ "PwmIsr_36",
  /* 311: */ "PwmIsr_37",
  /* 312: */ "PwmIsr_38",
  /* 313: */ "PwmIsr_39",
  /* 314: */ "PwmIsr_40",
  /* 315: */ "PwmIsr_41",
  /* 316: */ "PwmIsr_42",
  /* 317: */ "PwmIsr_43",
  /* 318: */ "PwmIsr_44",
  /* 319: */ "PwmIsr_45",
  /* 320: */ "PwmIsr_46",
  /* 321: */ "PwmIsr_47",
  /* 322: */ "PwmIsr_48",
  /* 323: */ "PwmIsr_49",
  /* 324: */ "SpiIsrTx_0",
  /* 325: */ "SpiIsrRx_0",
  /* 326: */ "SpiIsrTx_1",
  /* 327: */ "SpiIsrRx_1",
  /* 328: */ "SpiIsrTx_2",
  /* 329: */ "SpiIsrRx_2",
  /* 330: */ "SpiIsrTx_3",
  /* 331: */ "SpiIsrRx_3",
  /* 332: */ "SpiIsrTx_4",
  /* 333: */ "SpiIsrRx_4",
  /* 334: */ "SpiIsrTx_5",
  /* 335: */ "SpiIsrRx_5",
  /* 336: */ "SpiIsrTx_6",
  /* 337: */ "SpiIsrRx_6",
  /* 338: */ "SpiIsrTx_7",
  /* 339: */ "SpiIsrRx_7",
  /* 340: */ "SpiIsrTx_8",
  /* 341: */ "SpiIsrRx_8",
  /* 342: */ "SpiIsrTx_9",
  /* 343: */ "SpiIsrRx_9",
  /* 344: */ "SpiIsrTx_10",
  /* 345: */ "SpiIsrRx_10",
  /* 346: */ "SpiIsrTx_11",
  /* 347: */ "SpiIsrRx_11",
  /* 348: */ "SpiIsrTx_12",
  /* 349: */ "SpiIsrRx_12",
  /* 350: */ "SpiIsrTx_13",
  /* 351: */ "SpiIsrRx_13",
  /* 352: */ "SpiIsrTx_14",
  /* 353: */ "SpiIsrRx_14",
  /* 354: */ "SpiIsrTx_15",
  /* 355: */ "SpiIsrRx_15",
  /* 356: */ "SpiIsrTx_16",
  /* 357: */ "SpiIsrRx_16",
  /* 358: */ "SpiIsrTx_17",
  /* 359: */ "SpiIsrRx_17",
  /* 360: */ "SpiIsrTx_18",
  /* 361: */ "SpiIsrRx_18",
  /* 362: */ "SpiIsrTx_19",
  /* 363: */ "SpiIsrRx_19",
  /* 364: */ "SpiIsrTx_20",
  /* 365: */ "SpiIsrRx_20",
  /* 366: */ "SpiIsrTx_21",
  /* 367: */ "SpiIsrRx_21",
  /* 368: */ "SpiIsrTx_22",
  /* 369: */ "SpiIsrRx_22",
  /* 370: */ "SpiIsrTx_23",
  /* 371: */ "SpiIsrRx_23",
  /* 372: */ "SpiIsrTx_24",
  /* 373: */ "SpiIsrRx_24",
  /* 374: */ "SpiIsrTx_25",
  /* 375: */ "SpiIsrRx_25",
  /* 376: */ "SpiIsrTx_26",
  /* 377: */ "SpiIsrRx_26",
  /* 378: */ "SpiIsrTx_27",
  /* 379: */ "SpiIsrRx_27",
  /* 380: */ "SpiIsrTx_28",
  /* 381: */ "SpiIsrRx_28",
  /* 382: */ "SpiIsrTx_29",
  /* 383: */ "SpiIsrRx_29",
  /* 384: */ "SpiIsrTx_30",
  /* 385: */ "SpiIsrRx_30",
  /* 386: */ "SpiIsrTx_31",
  /* 387: */ "SpiIsrRx_31",
  /* 388: */ "SpiIsrTx_32",
  /* 389: */ "SpiIsrRx_32",
  /* 390: */ "SpiIsrTx_33",
  /* 391: */ "SpiIsrRx_33",
  /* 392: */ "SpiIsrTx_34",
  /* 393: */ "SpiIsrRx_34",
  /* 394: */ "SpiIsrTx_35",
  /* 395: */ "SpiIsrRx_35",
  /* 396: */ "SpiIsrTx_36",
  /* 397: */ "SpiIsrRx_36",
  /* 398: */ "SpiIsrTx_37",
  /* 399: */ "SpiIsrRx_37",
  /* 400: */ "SpiIsrTx_38",
  /* 401: */ "SpiIsrRx_38",
  /* 402: */ "SpiIsrTx_39",
  /* 403: */ "SpiIsrRx_39",
  /* 404: */ "SpiIsrTx_40",
  /* 405: */ "SpiIsrRx_40",
  /* 406: */ "SpiIsrTx_41",
  /* 407: */ "SpiIsrRx_41",
  /* 408: */ "SpiIsrTx_42",
  /* 409: */ "SpiIsrRx_42",
  /* 410: */ "SpiIsrTx_43",
  /* 411: */ "SpiIsrRx_43",
  /* 412: */ "SpiIsrTx_44",
  /* 413: */ "SpiIsrRx_44",
  /* 414: */ "SpiIsrTx_45",
  /* 415: */ "SpiIsrRx_45",
  /* 416: */ "SpiIsrTx_46",
  /* 417: */ "SpiIsrRx_46",
  /* 418: */ "SpiIsrTx_47",
  /* 419: */ "SpiIsrRx_47",
  /* 420: */ "SpiIsrTx_48",
  /* 421: */ "SpiIsrRx_48",
  /* 422: */ "SpiIsrTx_49",
  /* 423: */ "SpiIsrRx_49",
  /* 424: */ "CddIsr_0",
  /* 425: */ "CddIsr_1",
  /* 426: */ "CddIsr_2",
  /* 427: */ "CddIsr_3",
  /* 428: */ "CddIsr_4",
  /* 429: */ "CddIsr_5",
  /* 430: */ "CddIsr_6",
  /* 431: */ "CddIsr_7",
  /* 432: */ "CddIsr_8",
  /* 433: */ "CddIsr_9",
  /* 434: */ "CddIsr_10",
  /* 435: */ "CddIsr_11",
  /* 436: */ "CddIsr_12",
  /* 437: */ "CddIsr_13",
  /* 438: */ "CddIsr_14",
  /* 439: */ "CddIsr_15",
  /* 440: */ "CddIsr_16",
  /* 441: */ "CddIsr_17",
  /* 442: */ "CddIsr_18",
  /* 443: */ "CddIsr_19",
  /* 444: */ "CddIsr_20",
  /* 445: */ "CddIsr_21",
  /* 446: */ "CddIsr_22",
  /* 447: */ "CddIsr_23",
  /* 448: */ "CddIsr_24",
  /* 449: */ "CddIsr_25",
  /* 450: */ "CddIsr_26",
  /* 451: */ "CddIsr_27",
  /* 452: */ "CddIsr_28",
  /* 453: */ "CddIsr_29",
  /* 454: */ "CddIsr_30",
  /* 455: */ "CddIsr_31",
  /* 456: */ "CddIsr_32",
  /* 457: */ "CddIsr_33",
  /* 458: */ "CddIsr_34",
  /* 459: */ "CddIsr_35",
  /* 460: */ "CddIsr_36",
  /* 461: */ "CddIsr_37",
  /* 462: */ "CddIsr_38",
  /* 463: */ "CddIsr_39",
  /* 464: */ "CddIsr_40",
  /* 465: */ "CddIsr_41",
  /* 466: */ "CddIsr_42",
  /* 467: */ "CddIsr_43",
  /* 468: */ "CddIsr_44",
  /* 469: */ "CddIsr_45",
  /* 470: */ "CddIsr_46",
  /* 471: */ "CddIsr_47",
  /* 472: */ "CddIsr_48",
  /* 473: */ "CddIsr_49",
};

osuint8 VTTOs_GetInterruptName(osint32 isr, const char ** interruptName)
{
  int returnValue;

  if (isr >= oskNumberOfInterruptSources)
  {
    (*interruptName) = "Unknown IRQ";
    returnValue = VTTOS_IRQ_UNKNOWN;
  }
  else
  {
    (*interruptName) = ISRNameTable[isr];
    returnValue = VTTOS_IRQ_OK;
  }
  return returnValue;
}

/* MISRA RULE 8.10 VIOLATION: osConfigBlock is accessed by several modules in many configurations.
*  Declaring this variable static in the other cases would increase code complexity too much.
*/
osqROM0 osqROM1 const osqROM2 tsConfigBlock osqROM3 osConfigBlock = /* PRQA S 1504 */ 
{
   /* Frame */
   {0x82, 0x2A, 0x0C, 0xC4}, /* aucMagicNumber */
   (osuint16)((((sizeof(osConfigBlock)) & 0xFF) << 8)|
              (( sizeof(osConfigBlock))         >> 8)), /* Length (little endian) */
   0x000A,                /*  = CANoeVTT */
   osdVrmMajRelNumRef,    /* MajorVersion */
   osdVrmMinRelNumRef,    /* MinorVersion */
   (osuint16)1,           /* ConfigBlockVersion */
   (osuint16)1, /* UserConfigVersion */
   /* cargo --------------------------------------------------------------- */
   &osConfigBlock,
   /* start addresses of sub-containers (fixed number) */
   &(osConfigBlock.uiNumberOfTasks),        /* Sub-Container 0 */
   (osConfigBlock._aulTaskStartAddress),        /* Sub-Container 1 */
   (osConfigBlock._aucTaskPreemptive),          /* Sub-Container 2 */
   (osConfigBlock._aucTaskTrusted),          /* Sub-Container 3 */
   (osConfigBlock._aulTaskStackStartAddress),   /* Sub-Container 4 */
   (osConfigBlock._aulTaskStackEndAddress),     /* Sub-Container 5 */
   (osConfigBlock._acTaskToAppl),            /* Sub-Container 6 */
   (osConfigBlock._aucIsrTrusted),           /* Sub-Container 7 */
   (osConfigBlock._acIsrToAppl),             /* Sub-Container 8 */
   /* Sub-Container 0 */
   osdNumberOfAllTasks,
   osdNumberOfCat2ISRs,
   osdNumberOfTrustedFunctions,
   osdNumberOfNonTrustedFunctions,
   osdNumberOfApplications,
   osdNumberOfPeripheralRegions,
   osdStackUsageMeasurement,
   /* Sub-Container 1, task start addresses */
   {
      &SchM_Taskfunc,
      &IO_Taskfunc,
      &My_Taskfunc,
      &Init_Taskfunc,
      (osTaskFctType)0
   },
   /* Sub-Container 2, task preemptiveness */
   {
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypePreempt,
      osdTaskTypeNonPreempt,
      0
   },
   /* Sub-Container 3, task trusted */
   {
      0,
      0,
      0,
      0,
      0
   },
   /* Sub-Container 4, stack start address */
   {
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0
   },
   /* Sub-Container 5, stack end addresses */
   {
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0,  /* stacks are managed by the CANoeEmuProcessor */
      (osStackPtrType)0
   },
   /* Sub-Container 6, translation table: task -> os-application */
   {
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION
   },
   /* Sub-Container 7, ISR trusted */
   {
   0,   /* CanIsrWakeup_0 */
   0,   /* CanIsrTx_0 */
   0,   /* CanIsrErr_0 */
   0,   /* CanIsrRx_0 */
   1,   /* osTimerInterrupt */
      0
   },
   /* Sub-Container 8, translation table: isr -> os-application */
   {
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION,
      INVALID_OSAPPLICATION
   },
(osuint32)0 /* uiCheckSum */
};
StatusType osStartCOMExtension(void)
{
   return E_OK;
};


/* END OF C:\CanCollege\AUTOSAR4\_S5_MemoryAbstraction\Appl\GenDataVtt\tcb.c */

