/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\TRAINI~1.VMA\AppData\Local\Temp\Cfg_Gen-1519017006631-0\OsProxyFiles-1519017056406-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Mon Feb 19 06:11:01 2018 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\CanCollege\Autosar4\_S6_Diagnostics\Appl\GenDataVtt\msg.c */

