/* MISRA RULE 19.15 not violated: The QAC-Tool states a violation of rule 19.15 with
 * message 0883 below. Anyhow, there is a double include prevention and therefore,
 * the message is considered to be wrong. */
/* double include preventer */
#ifndef _TRUSTCFT_H      /* PRQA S 0883 EOF */ /* see MISRA comment above */
#define _TRUSTCFT_H
/* file: trustfct.h, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: C:\Users\TRAINI~1.VMA\AppData\Local\Temp\Cfg_Gen-1519017006631-0\OsProxyFiles-1519017056406-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Mon Feb 19 06:11:01 2018 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif



		/* Trusted functions not used in SC1*/

/* END OF C:\CanCollege\Autosar4\_S6_Diagnostics\Appl\GenDataVtt\trustfct.h */

#endif /* _TRUSTCFT_H double include preventer */
