/**********************************************************************************************************************
 *  DO NOT EDIT!!! This file is automatically generated.
 *  -------------------------------------------------------------------------------------------------------------------
 *  COPYRIGHT
 *  -------------------------------------------------------------------------------------------------------------------
 *  Copyright (c) 2013-2015 by Vector Informatik GmbH. All rights reserved.
 *  -------------------------------------------------------------------------------------------------------------------
 *  FILE DESCRIPTION
 *  -------------------------------------------------------------------------------------------------------------------
 *          File:  Vtt_Rte.h
 *  ECU-Instance:  MyECU
 *  Generated at:  2018-02-19  06:11:17
 *
 *     Generator:  VTT 1.1.19.0
 *
 *   Description:  Obsolete file, that was formerly used as header files for the VTT Hooks
 *                 The file was replaced by Vtt_Hook.h
 *********************************************************************************************************************/
 #ifndef VTT_RTE_H
 #define VTT_RTE_H

#define VttRte_OnStateChange(action, oldState, newState)

#endif