/* file: msg.c, automatically generated by gencanoe.exe, Version: 5.02 */
/* configuration read from: D:\TEMP\Cfg_Gen-1461688456759-1\OsProxyFiles-1461688568152-0\Os_ActiveEcuC.arxml.oil */
/* generation at  : Tue Apr 26 18:36:14 2016 */
/* Unlimited license 1234567890 for CANoeEmu Generic License */
/* Implementation: CANoeOsekEmu */
/* Version of general code: 5.31 */

#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif
#define osdVrmGenMajRelNum 5
#define osdVrmGenMinRelNum 2
#if defined USE_QUOTE_INCLUDES
 #include "vrm.h"
#else
 #include <vrm.h>
#endif

#include <Os.h>


/* END OF C:\CanCollege\Autosar4\S4_ModeManagment\Appl\GenDataVtt\msg.c */

